// Code generated by protoc-gen-go.
// source: TSCHCommandArchives.proto
// DO NOT EDIT!

/*
Package TSCH is a generated protocol buffer package.

It is generated from these files:
	TSCHCommandArchives.proto

It has these top-level messages:
	CommandSetChartTypeArchive
	PropertyMutationUndoTupleArchive
	StyleSwapUndoTupleArchive
	CommandStyleSwapArchive
	CommandSetSeriesNameArchive
	CommandSetCategoryNameArchive
	CommandAddGridRowsArchive
	CommandAddGridColumnsArchive
	CommandMoveGridRowsArchive
	CommandMoveGridColumnsArchive
	CommandDeleteGridRowsArchive
	CommandDeleteGridColumnsArchive
	CommandSetPreviewLocArchive
	CommandSetGridValueArchive
	CommandSetGridDirectionArchive
	CommandSetSeriesTypeArchive
	CommandSetScatterFormatArchive
	CommandSetMultiDataSetIndexArchive
	CommandSetLegendFrameArchive
	CommandSetPieWedgeExplosion
	SynchronousCommandArchive
	CommandReplaceAllArchive
	CommandChartApplyTheme
	CommandChartApplyPreset
	CommandCleanupGeometryArchive
	ChartCommandArchive
	CommandReplaceGridValuesArchive
	CommandReplaceThemePresetArchive
	CommandInvalidateWPCaches
*/
package TSCH

import proto "code.google.com/p/goprotobuf/proto"
import math "math"
import "github.com/dunhamsteve/iwork/proto/TSP"
import "github.com/dunhamsteve/iwork/proto/TSK"
import "github.com/dunhamsteve/iwork/proto/TSS"

// discarding unused import TSD "TSDArchives.pb"

// discarding unused import TSCH_Generated "TSCHArchives.GEN.pb"
// discarding unused import TSCH1 "TSCH3DArchives.pb"
// discarding unused import TSCH3 "TSCHArchives.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type StyleOwnerType int32

const (
	StyleOwnerType_chart_info   StyleOwnerType = 1
	StyleOwnerType_legend_model StyleOwnerType = 2
	StyleOwnerType_chart_axis   StyleOwnerType = 3
	StyleOwnerType_chart_series StyleOwnerType = 4
)

var StyleOwnerType_name = map[int32]string{
	1: "chart_info",
	2: "legend_model",
	3: "chart_axis",
	4: "chart_series",
}
var StyleOwnerType_value = map[string]int32{
	"chart_info":   1,
	"legend_model": 2,
	"chart_axis":   3,
	"chart_series": 4,
}

func (x StyleOwnerType) Enum() *StyleOwnerType {
	p := new(StyleOwnerType)
	*p = x
	return p
}
func (x StyleOwnerType) String() string {
	return proto.EnumName(StyleOwnerType_name, int32(x))
}
func (x *StyleOwnerType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StyleOwnerType_value, data, "StyleOwnerType")
	if err != nil {
		return err
	}
	*x = StyleOwnerType(value)
	return nil
}

type StyleSwapType int32

const (
	StyleSwapType_chart_style             StyleSwapType = 1
	StyleSwapType_chart_non_style         StyleSwapType = 2
	StyleSwapType_legend_style            StyleSwapType = 3
	StyleSwapType_legend_non_style        StyleSwapType = 4
	StyleSwapType_value_axis_style        StyleSwapType = 5
	StyleSwapType_value_axis_non_style    StyleSwapType = 6
	StyleSwapType_category_axis_style     StyleSwapType = 7
	StyleSwapType_category_axis_non_style StyleSwapType = 8
	StyleSwapType_series_theme_style      StyleSwapType = 9
	StyleSwapType_series_private_style    StyleSwapType = 10
	StyleSwapType_series_non_style        StyleSwapType = 11
	StyleSwapType_paragraph_style         StyleSwapType = 12
)

var StyleSwapType_name = map[int32]string{
	1:  "chart_style",
	2:  "chart_non_style",
	3:  "legend_style",
	4:  "legend_non_style",
	5:  "value_axis_style",
	6:  "value_axis_non_style",
	7:  "category_axis_style",
	8:  "category_axis_non_style",
	9:  "series_theme_style",
	10: "series_private_style",
	11: "series_non_style",
	12: "paragraph_style",
}
var StyleSwapType_value = map[string]int32{
	"chart_style":             1,
	"chart_non_style":         2,
	"legend_style":            3,
	"legend_non_style":        4,
	"value_axis_style":        5,
	"value_axis_non_style":    6,
	"category_axis_style":     7,
	"category_axis_non_style": 8,
	"series_theme_style":      9,
	"series_private_style":    10,
	"series_non_style":        11,
	"paragraph_style":         12,
}

func (x StyleSwapType) Enum() *StyleSwapType {
	p := new(StyleSwapType)
	*p = x
	return p
}
func (x StyleSwapType) String() string {
	return proto.EnumName(StyleSwapType_name, int32(x))
}
func (x *StyleSwapType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StyleSwapType_value, data, "StyleSwapType")
	if err != nil {
		return err
	}
	*x = StyleSwapType(value)
	return nil
}

type ApplyPresetBehavior int32

const (
	ApplyPresetBehavior_remove_overrides    ApplyPresetBehavior = 1
	ApplyPresetBehavior_preserve_overrides  ApplyPresetBehavior = 2
	ApplyPresetBehavior_preserve_appearance ApplyPresetBehavior = 3
)

var ApplyPresetBehavior_name = map[int32]string{
	1: "remove_overrides",
	2: "preserve_overrides",
	3: "preserve_appearance",
}
var ApplyPresetBehavior_value = map[string]int32{
	"remove_overrides":    1,
	"preserve_overrides":  2,
	"preserve_appearance": 3,
}

func (x ApplyPresetBehavior) Enum() *ApplyPresetBehavior {
	p := new(ApplyPresetBehavior)
	*p = x
	return p
}
func (x ApplyPresetBehavior) String() string {
	return proto.EnumName(ApplyPresetBehavior_name, int32(x))
}
func (x *ApplyPresetBehavior) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApplyPresetBehavior_value, data, "ApplyPresetBehavior")
	if err != nil {
		return err
	}
	*x = ApplyPresetBehavior(value)
	return nil
}

type CommandSetChartTypeArchive struct {
	Super                   *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OldChartType            *ChartType     `protobuf:"varint,2,req,name=oldChartType,enum=ChartType" json:"oldChartType,omitempty"`
	NewChartType            *ChartType     `protobuf:"varint,3,req,name=newChartType,enum=ChartType" json:"newChartType,omitempty"`
	InfoGeometryCommand     *TSP.Reference       `protobuf:"bytes,5,opt,name=info_geometry_command" json:"info_geometry_command,omitempty"`
	AnchorAttachmentCommand *TSP.Reference       `protobuf:"bytes,6,opt,name=anchor_attachment_command" json:"anchor_attachment_command,omitempty"`
	OriginalLegendRect      *RectArchive   `protobuf:"bytes,7,opt,name=original_legend_rect" json:"original_legend_rect,omitempty"`
	XXX_unrecognized        []byte               `json:"-"`
}

func (m *CommandSetChartTypeArchive) Reset()         { *m = CommandSetChartTypeArchive{} }
func (m *CommandSetChartTypeArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetChartTypeArchive) ProtoMessage()    {}

func (m *CommandSetChartTypeArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetChartTypeArchive) GetOldChartType() ChartType {
	if m != nil && m.OldChartType != nil {
		return *m.OldChartType
	}
	return ChartType_undefinedChartType
}

func (m *CommandSetChartTypeArchive) GetNewChartType() ChartType {
	if m != nil && m.NewChartType != nil {
		return *m.NewChartType
	}
	return ChartType_undefinedChartType
}

func (m *CommandSetChartTypeArchive) GetInfoGeometryCommand() *TSP.Reference {
	if m != nil {
		return m.InfoGeometryCommand
	}
	return nil
}

func (m *CommandSetChartTypeArchive) GetAnchorAttachmentCommand() *TSP.Reference {
	if m != nil {
		return m.AnchorAttachmentCommand
	}
	return nil
}

func (m *CommandSetChartTypeArchive) GetOriginalLegendRect() *RectArchive {
	if m != nil {
		return m.OriginalLegendRect
	}
	return nil
}

type PropertyMutationUndoTupleArchive struct {
	ChartInfo        *TSP.Reference  `protobuf:"bytes,1,opt,name=chart_info" json:"chart_info,omitempty"`
	StyleOwnerType   *StyleOwnerType `protobuf:"varint,2,opt,name=style_owner_type,enum=StyleOwnerType" json:"style_owner_type,omitempty"`
	Index            *uint32         `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	OldStyle         *TSP.Reference  `protobuf:"bytes,4,opt,name=old_style" json:"old_style,omitempty"`
	NewStyle         *TSP.Reference  `protobuf:"bytes,5,opt,name=new_style" json:"new_style,omitempty"`
	OldNonStyle      *TSP.Reference  `protobuf:"bytes,6,opt,name=old_non_style" json:"old_non_style,omitempty"`
	NewNonStyle      *TSP.Reference  `protobuf:"bytes,7,opt,name=new_non_style" json:"new_non_style,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *PropertyMutationUndoTupleArchive) Reset()         { *m = PropertyMutationUndoTupleArchive{} }
func (m *PropertyMutationUndoTupleArchive) String() string { return proto.CompactTextString(m) }
func (*PropertyMutationUndoTupleArchive) ProtoMessage()    {}

func (m *PropertyMutationUndoTupleArchive) GetChartInfo() *TSP.Reference {
	if m != nil {
		return m.ChartInfo
	}
	return nil
}

func (m *PropertyMutationUndoTupleArchive) GetStyleOwnerType() StyleOwnerType {
	if m != nil && m.StyleOwnerType != nil {
		return *m.StyleOwnerType
	}
	return StyleOwnerType_chart_info
}

func (m *PropertyMutationUndoTupleArchive) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *PropertyMutationUndoTupleArchive) GetOldStyle() *TSP.Reference {
	if m != nil {
		return m.OldStyle
	}
	return nil
}

func (m *PropertyMutationUndoTupleArchive) GetNewStyle() *TSP.Reference {
	if m != nil {
		return m.NewStyle
	}
	return nil
}

func (m *PropertyMutationUndoTupleArchive) GetOldNonStyle() *TSP.Reference {
	if m != nil {
		return m.OldNonStyle
	}
	return nil
}

func (m *PropertyMutationUndoTupleArchive) GetNewNonStyle() *TSP.Reference {
	if m != nil {
		return m.NewNonStyle
	}
	return nil
}

type StyleSwapUndoTupleArchive struct {
	ChartInfo        *TSP.Reference `protobuf:"bytes,1,opt,name=chart_info" json:"chart_info,omitempty"`
	SwapType         *StyleSwapType `protobuf:"varint,2,opt,name=swap_type,enum=StyleSwapType" json:"swap_type,omitempty"`
	Index            *uint32        `protobuf:"varint,3,opt,name=index" json:"index,omitempty"`
	OldValue         *TSP.Reference `protobuf:"bytes,4,opt,name=old_value" json:"old_value,omitempty"`
	NewValue         *TSP.Reference `protobuf:"bytes,5,opt,name=new_value" json:"new_value,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *StyleSwapUndoTupleArchive) Reset()         { *m = StyleSwapUndoTupleArchive{} }
func (m *StyleSwapUndoTupleArchive) String() string { return proto.CompactTextString(m) }
func (*StyleSwapUndoTupleArchive) ProtoMessage()    {}

func (m *StyleSwapUndoTupleArchive) GetChartInfo() *TSP.Reference {
	if m != nil {
		return m.ChartInfo
	}
	return nil
}

func (m *StyleSwapUndoTupleArchive) GetSwapType() StyleSwapType {
	if m != nil && m.SwapType != nil {
		return *m.SwapType
	}
	return StyleSwapType_chart_style
}

func (m *StyleSwapUndoTupleArchive) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *StyleSwapUndoTupleArchive) GetOldValue() *TSP.Reference {
	if m != nil {
		return m.OldValue
	}
	return nil
}

func (m *StyleSwapUndoTupleArchive) GetNewValue() *TSP.Reference {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type CommandStyleSwapArchive struct {
	Super            *ChartCommandArchive         `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	UndoTuples       []*StyleSwapUndoTupleArchive `protobuf:"bytes,2,rep,name=undo_tuples" json:"undo_tuples,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (m *CommandStyleSwapArchive) Reset()         { *m = CommandStyleSwapArchive{} }
func (m *CommandStyleSwapArchive) String() string { return proto.CompactTextString(m) }
func (*CommandStyleSwapArchive) ProtoMessage()    {}

func (m *CommandStyleSwapArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandStyleSwapArchive) GetUndoTuples() []*StyleSwapUndoTupleArchive {
	if m != nil {
		return m.UndoTuples
	}
	return nil
}

type CommandSetSeriesNameArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	SeriesIndex      *uint32              `protobuf:"varint,2,req,name=seriesIndex" json:"seriesIndex,omitempty"`
	OldName          *string              `protobuf:"bytes,3,req,name=oldName" json:"oldName,omitempty"`
	NewName          *string              `protobuf:"bytes,4,req,name=newName" json:"newName,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetSeriesNameArchive) Reset()         { *m = CommandSetSeriesNameArchive{} }
func (m *CommandSetSeriesNameArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetSeriesNameArchive) ProtoMessage()    {}

func (m *CommandSetSeriesNameArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetSeriesNameArchive) GetSeriesIndex() uint32 {
	if m != nil && m.SeriesIndex != nil {
		return *m.SeriesIndex
	}
	return 0
}

func (m *CommandSetSeriesNameArchive) GetOldName() string {
	if m != nil && m.OldName != nil {
		return *m.OldName
	}
	return ""
}

func (m *CommandSetSeriesNameArchive) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

type CommandSetCategoryNameArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	CategoryIndex    *uint32              `protobuf:"varint,2,req,name=categoryIndex" json:"categoryIndex,omitempty"`
	OldName          *string              `protobuf:"bytes,3,req,name=oldName" json:"oldName,omitempty"`
	NewName          *string              `protobuf:"bytes,4,req,name=newName" json:"newName,omitempty"`
	IsMultiDataIndex *bool                `protobuf:"varint,5,opt,name=isMultiDataIndex" json:"isMultiDataIndex,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetCategoryNameArchive) Reset()         { *m = CommandSetCategoryNameArchive{} }
func (m *CommandSetCategoryNameArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetCategoryNameArchive) ProtoMessage()    {}

func (m *CommandSetCategoryNameArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetCategoryNameArchive) GetCategoryIndex() uint32 {
	if m != nil && m.CategoryIndex != nil {
		return *m.CategoryIndex
	}
	return 0
}

func (m *CommandSetCategoryNameArchive) GetOldName() string {
	if m != nil && m.OldName != nil {
		return *m.OldName
	}
	return ""
}

func (m *CommandSetCategoryNameArchive) GetNewName() string {
	if m != nil && m.NewName != nil {
		return *m.NewName
	}
	return ""
}

func (m *CommandSetCategoryNameArchive) GetIsMultiDataIndex() bool {
	if m != nil && m.IsMultiDataIndex != nil {
		return *m.IsMultiDataIndex
	}
	return false
}

type CommandAddGridRowsArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Location         *uint32              `protobuf:"varint,2,req,name=location" json:"location,omitempty"`
	Length           *uint32              `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	Name             []string             `protobuf:"bytes,4,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandAddGridRowsArchive) Reset()         { *m = CommandAddGridRowsArchive{} }
func (m *CommandAddGridRowsArchive) String() string { return proto.CompactTextString(m) }
func (*CommandAddGridRowsArchive) ProtoMessage()    {}

func (m *CommandAddGridRowsArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandAddGridRowsArchive) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *CommandAddGridRowsArchive) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *CommandAddGridRowsArchive) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type CommandAddGridColumnsArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Location         *uint32              `protobuf:"varint,2,req,name=location" json:"location,omitempty"`
	Length           *uint32              `protobuf:"varint,3,opt,name=length" json:"length,omitempty"`
	Name             []string             `protobuf:"bytes,4,rep,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandAddGridColumnsArchive) Reset()         { *m = CommandAddGridColumnsArchive{} }
func (m *CommandAddGridColumnsArchive) String() string { return proto.CompactTextString(m) }
func (*CommandAddGridColumnsArchive) ProtoMessage()    {}

func (m *CommandAddGridColumnsArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandAddGridColumnsArchive) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *CommandAddGridColumnsArchive) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *CommandAddGridColumnsArchive) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type CommandMoveGridRowsArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Location         *uint32              `protobuf:"varint,2,req,name=location" json:"location,omitempty"`
	Length           *uint32              `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Afterrow         *int32               `protobuf:"varint,4,req,name=afterrow" json:"afterrow,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandMoveGridRowsArchive) Reset()         { *m = CommandMoveGridRowsArchive{} }
func (m *CommandMoveGridRowsArchive) String() string { return proto.CompactTextString(m) }
func (*CommandMoveGridRowsArchive) ProtoMessage()    {}

func (m *CommandMoveGridRowsArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandMoveGridRowsArchive) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *CommandMoveGridRowsArchive) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *CommandMoveGridRowsArchive) GetAfterrow() int32 {
	if m != nil && m.Afterrow != nil {
		return *m.Afterrow
	}
	return 0
}

type CommandMoveGridColumnsArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Location         *uint32              `protobuf:"varint,2,req,name=location" json:"location,omitempty"`
	Length           *uint32              `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Aftercolumn      *int32               `protobuf:"varint,4,req,name=aftercolumn" json:"aftercolumn,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandMoveGridColumnsArchive) Reset()         { *m = CommandMoveGridColumnsArchive{} }
func (m *CommandMoveGridColumnsArchive) String() string { return proto.CompactTextString(m) }
func (*CommandMoveGridColumnsArchive) ProtoMessage()    {}

func (m *CommandMoveGridColumnsArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandMoveGridColumnsArchive) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *CommandMoveGridColumnsArchive) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *CommandMoveGridColumnsArchive) GetAftercolumn() int32 {
	if m != nil && m.Aftercolumn != nil {
		return *m.Aftercolumn
	}
	return 0
}

type CommandDeleteGridRowsArchive struct {
	Super            *ChartCommandArchive                     `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Location         *uint32                                  `protobuf:"varint,2,req,name=location" json:"location,omitempty"`
	Length           *uint32                                  `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Names            []string                                 `protobuf:"bytes,4,rep,name=names" json:"names,omitempty"`
	ValueRow         []*CommandDeleteGridRowsArchive_ValueRow `protobuf:"bytes,6,rep,name=value_row" json:"value_row,omitempty"`
	RemovedAllRows   *bool                                    `protobuf:"varint,7,opt,name=removed_all_rows" json:"removed_all_rows,omitempty"`
	ColumnNames      []string                                 `protobuf:"bytes,8,rep,name=column_names" json:"column_names,omitempty"`
	XXX_unrecognized []byte                                   `json:"-"`
}

func (m *CommandDeleteGridRowsArchive) Reset()         { *m = CommandDeleteGridRowsArchive{} }
func (m *CommandDeleteGridRowsArchive) String() string { return proto.CompactTextString(m) }
func (*CommandDeleteGridRowsArchive) ProtoMessage()    {}

func (m *CommandDeleteGridRowsArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandDeleteGridRowsArchive) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *CommandDeleteGridRowsArchive) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *CommandDeleteGridRowsArchive) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *CommandDeleteGridRowsArchive) GetValueRow() []*CommandDeleteGridRowsArchive_ValueRow {
	if m != nil {
		return m.ValueRow
	}
	return nil
}

func (m *CommandDeleteGridRowsArchive) GetRemovedAllRows() bool {
	if m != nil && m.RemovedAllRows != nil {
		return *m.RemovedAllRows
	}
	return false
}

func (m *CommandDeleteGridRowsArchive) GetColumnNames() []string {
	if m != nil {
		return m.ColumnNames
	}
	return nil
}

type CommandDeleteGridRowsArchive_ValueRow struct {
	Value            []float64 `protobuf:"fixed64,5,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CommandDeleteGridRowsArchive_ValueRow) Reset()         { *m = CommandDeleteGridRowsArchive_ValueRow{} }
func (m *CommandDeleteGridRowsArchive_ValueRow) String() string { return proto.CompactTextString(m) }
func (*CommandDeleteGridRowsArchive_ValueRow) ProtoMessage()    {}

func (m *CommandDeleteGridRowsArchive_ValueRow) GetValue() []float64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type CommandDeleteGridColumnsArchive struct {
	Super             *ChartCommandArchive                        `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Location          *uint32                                     `protobuf:"varint,2,req,name=location" json:"location,omitempty"`
	Length            *uint32                                     `protobuf:"varint,3,req,name=length" json:"length,omitempty"`
	Names             []string                                    `protobuf:"bytes,4,rep,name=names" json:"names,omitempty"`
	ValueRow          []*CommandDeleteGridColumnsArchive_ValueRow `protobuf:"bytes,6,rep,name=value_row" json:"value_row,omitempty"`
	RemovedAllColumns *bool                                       `protobuf:"varint,7,opt,name=removed_all_columns" json:"removed_all_columns,omitempty"`
	RowNames          []string                                    `protobuf:"bytes,8,rep,name=row_names" json:"row_names,omitempty"`
	XXX_unrecognized  []byte                                      `json:"-"`
}

func (m *CommandDeleteGridColumnsArchive) Reset()         { *m = CommandDeleteGridColumnsArchive{} }
func (m *CommandDeleteGridColumnsArchive) String() string { return proto.CompactTextString(m) }
func (*CommandDeleteGridColumnsArchive) ProtoMessage()    {}

func (m *CommandDeleteGridColumnsArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandDeleteGridColumnsArchive) GetLocation() uint32 {
	if m != nil && m.Location != nil {
		return *m.Location
	}
	return 0
}

func (m *CommandDeleteGridColumnsArchive) GetLength() uint32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func (m *CommandDeleteGridColumnsArchive) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *CommandDeleteGridColumnsArchive) GetValueRow() []*CommandDeleteGridColumnsArchive_ValueRow {
	if m != nil {
		return m.ValueRow
	}
	return nil
}

func (m *CommandDeleteGridColumnsArchive) GetRemovedAllColumns() bool {
	if m != nil && m.RemovedAllColumns != nil {
		return *m.RemovedAllColumns
	}
	return false
}

func (m *CommandDeleteGridColumnsArchive) GetRowNames() []string {
	if m != nil {
		return m.RowNames
	}
	return nil
}

type CommandDeleteGridColumnsArchive_ValueRow struct {
	Value            []float64 `protobuf:"fixed64,5,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CommandDeleteGridColumnsArchive_ValueRow) Reset() {
	*m = CommandDeleteGridColumnsArchive_ValueRow{}
}
func (m *CommandDeleteGridColumnsArchive_ValueRow) String() string { return proto.CompactTextString(m) }
func (*CommandDeleteGridColumnsArchive_ValueRow) ProtoMessage()    {}

func (m *CommandDeleteGridColumnsArchive_ValueRow) GetValue() []float64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type CommandSetPreviewLocArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OldLoc           *TSP.Point           `protobuf:"bytes,2,req,name=old_loc" json:"old_loc,omitempty"`
	NewLoc           *TSP.Point           `protobuf:"bytes,3,req,name=new_loc" json:"new_loc,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetPreviewLocArchive) Reset()         { *m = CommandSetPreviewLocArchive{} }
func (m *CommandSetPreviewLocArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetPreviewLocArchive) ProtoMessage()    {}

func (m *CommandSetPreviewLocArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetPreviewLocArchive) GetOldLoc() *TSP.Point {
	if m != nil {
		return m.OldLoc
	}
	return nil
}

func (m *CommandSetPreviewLocArchive) GetNewLoc() *TSP.Point {
	if m != nil {
		return m.NewLoc
	}
	return nil
}

type CommandSetGridValueArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Rowindex         *uint32              `protobuf:"varint,2,req,name=rowindex" json:"rowindex,omitempty"`
	Columnindex      *uint32              `protobuf:"varint,3,req,name=columnindex" json:"columnindex,omitempty"`
	Oldvalue         *float64             `protobuf:"fixed64,4,req,name=oldvalue" json:"oldvalue,omitempty"`
	Newvalue         *float64             `protobuf:"fixed64,5,req,name=newvalue" json:"newvalue,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetGridValueArchive) Reset()         { *m = CommandSetGridValueArchive{} }
func (m *CommandSetGridValueArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetGridValueArchive) ProtoMessage()    {}

func (m *CommandSetGridValueArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetGridValueArchive) GetRowindex() uint32 {
	if m != nil && m.Rowindex != nil {
		return *m.Rowindex
	}
	return 0
}

func (m *CommandSetGridValueArchive) GetColumnindex() uint32 {
	if m != nil && m.Columnindex != nil {
		return *m.Columnindex
	}
	return 0
}

func (m *CommandSetGridValueArchive) GetOldvalue() float64 {
	if m != nil && m.Oldvalue != nil {
		return *m.Oldvalue
	}
	return 0
}

func (m *CommandSetGridValueArchive) GetNewvalue() float64 {
	if m != nil && m.Newvalue != nil {
		return *m.Newvalue
	}
	return 0
}

type CommandSetGridDirectionArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OldDirection     *uint32              `protobuf:"varint,2,req,name=old_direction" json:"old_direction,omitempty"`
	NewDirection     *uint32              `protobuf:"varint,3,req,name=new_direction" json:"new_direction,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetGridDirectionArchive) Reset()         { *m = CommandSetGridDirectionArchive{} }
func (m *CommandSetGridDirectionArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetGridDirectionArchive) ProtoMessage()    {}

func (m *CommandSetGridDirectionArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetGridDirectionArchive) GetOldDirection() uint32 {
	if m != nil && m.OldDirection != nil {
		return *m.OldDirection
	}
	return 0
}

func (m *CommandSetGridDirectionArchive) GetNewDirection() uint32 {
	if m != nil && m.NewDirection != nil {
		return *m.NewDirection
	}
	return 0
}

type CommandSetSeriesTypeArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Seriesindex      *uint32              `protobuf:"varint,2,req,name=seriesindex" json:"seriesindex,omitempty"`
	Oldtype          *uint32              `protobuf:"varint,3,req,name=oldtype" json:"oldtype,omitempty"`
	Newtype          *uint32              `protobuf:"varint,4,req,name=newtype" json:"newtype,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetSeriesTypeArchive) Reset()         { *m = CommandSetSeriesTypeArchive{} }
func (m *CommandSetSeriesTypeArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetSeriesTypeArchive) ProtoMessage()    {}

func (m *CommandSetSeriesTypeArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetSeriesTypeArchive) GetSeriesindex() uint32 {
	if m != nil && m.Seriesindex != nil {
		return *m.Seriesindex
	}
	return 0
}

func (m *CommandSetSeriesTypeArchive) GetOldtype() uint32 {
	if m != nil && m.Oldtype != nil {
		return *m.Oldtype
	}
	return 0
}

func (m *CommandSetSeriesTypeArchive) GetNewtype() uint32 {
	if m != nil && m.Newtype != nil {
		return *m.Newtype
	}
	return 0
}

type CommandSetScatterFormatArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Oldformat        *uint32              `protobuf:"varint,3,req,name=oldformat" json:"oldformat,omitempty"`
	Newformat        *uint32              `protobuf:"varint,4,req,name=newformat" json:"newformat,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetScatterFormatArchive) Reset()         { *m = CommandSetScatterFormatArchive{} }
func (m *CommandSetScatterFormatArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetScatterFormatArchive) ProtoMessage()    {}

func (m *CommandSetScatterFormatArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetScatterFormatArchive) GetOldformat() uint32 {
	if m != nil && m.Oldformat != nil {
		return *m.Oldformat
	}
	return 0
}

func (m *CommandSetScatterFormatArchive) GetNewformat() uint32 {
	if m != nil && m.Newformat != nil {
		return *m.Newformat
	}
	return 0
}

type CommandSetMultiDataSetIndexArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Oldindex         *uint32              `protobuf:"varint,2,req,name=oldindex" json:"oldindex,omitempty"`
	Newindex         *uint32              `protobuf:"varint,3,req,name=newindex" json:"newindex,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetMultiDataSetIndexArchive) Reset()         { *m = CommandSetMultiDataSetIndexArchive{} }
func (m *CommandSetMultiDataSetIndexArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetMultiDataSetIndexArchive) ProtoMessage()    {}

func (m *CommandSetMultiDataSetIndexArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetMultiDataSetIndexArchive) GetOldindex() uint32 {
	if m != nil && m.Oldindex != nil {
		return *m.Oldindex
	}
	return 0
}

func (m *CommandSetMultiDataSetIndexArchive) GetNewindex() uint32 {
	if m != nil && m.Newindex != nil {
		return *m.Newindex
	}
	return 0
}

type CommandSetLegendFrameArchive struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OldLegendFrame   *RectArchive   `protobuf:"bytes,2,req,name=old_legend_frame" json:"old_legend_frame,omitempty"`
	NewLegendFrame   *RectArchive   `protobuf:"bytes,3,req,name=new_legend_frame" json:"new_legend_frame,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandSetLegendFrameArchive) Reset()         { *m = CommandSetLegendFrameArchive{} }
func (m *CommandSetLegendFrameArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSetLegendFrameArchive) ProtoMessage()    {}

func (m *CommandSetLegendFrameArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetLegendFrameArchive) GetOldLegendFrame() *RectArchive {
	if m != nil {
		return m.OldLegendFrame
	}
	return nil
}

func (m *CommandSetLegendFrameArchive) GetNewLegendFrame() *RectArchive {
	if m != nil {
		return m.NewLegendFrame
	}
	return nil
}

type CommandSetPieWedgeExplosion struct {
	Super                   *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	InfoGeometryCommand     *TSP.Reference       `protobuf:"bytes,2,opt,name=info_geometry_command" json:"info_geometry_command,omitempty"`
	StyleMutationCommand    *TSP.Reference       `protobuf:"bytes,3,opt,name=style_mutation_command" json:"style_mutation_command,omitempty"`
	AnchorAttachmentCommand *TSP.Reference       `protobuf:"bytes,4,opt,name=anchor_attachment_command" json:"anchor_attachment_command,omitempty"`
	XXX_unrecognized        []byte               `json:"-"`
}

func (m *CommandSetPieWedgeExplosion) Reset()         { *m = CommandSetPieWedgeExplosion{} }
func (m *CommandSetPieWedgeExplosion) String() string { return proto.CompactTextString(m) }
func (*CommandSetPieWedgeExplosion) ProtoMessage()    {}

func (m *CommandSetPieWedgeExplosion) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandSetPieWedgeExplosion) GetInfoGeometryCommand() *TSP.Reference {
	if m != nil {
		return m.InfoGeometryCommand
	}
	return nil
}

func (m *CommandSetPieWedgeExplosion) GetStyleMutationCommand() *TSP.Reference {
	if m != nil {
		return m.StyleMutationCommand
	}
	return nil
}

func (m *CommandSetPieWedgeExplosion) GetAnchorAttachmentCommand() *TSP.Reference {
	if m != nil {
		return m.AnchorAttachmentCommand
	}
	return nil
}

type SynchronousCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Command          *TSP.Reference      `protobuf:"bytes,2,req,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *SynchronousCommandArchive) Reset()         { *m = SynchronousCommandArchive{} }
func (m *SynchronousCommandArchive) String() string { return proto.CompactTextString(m) }
func (*SynchronousCommandArchive) ProtoMessage()    {}

func (m *SynchronousCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *SynchronousCommandArchive) GetCommand() *TSP.Reference {
	if m != nil {
		return m.Command
	}
	return nil
}

type CommandReplaceAllArchive struct {
	Super            *TSK.ReplaceAllChildCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference                     `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	Commands         []*TSP.Reference                   `protobuf:"bytes,3,rep,name=commands" json:"commands,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *CommandReplaceAllArchive) Reset()         { *m = CommandReplaceAllArchive{} }
func (m *CommandReplaceAllArchive) String() string { return proto.CompactTextString(m) }
func (*CommandReplaceAllArchive) ProtoMessage()    {}

func (m *CommandReplaceAllArchive) GetSuper() *TSK.ReplaceAllChildCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandReplaceAllArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *CommandReplaceAllArchive) GetCommands() []*TSP.Reference {
	if m != nil {
		return m.Commands
	}
	return nil
}

type CommandChartApplyTheme struct {
	Super            *TSS.ApplyThemeChildCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference                     `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	SwapCommand      *TSP.Reference                     `protobuf:"bytes,3,opt,name=swap_command" json:"swap_command,omitempty"`
	Preset           *TSP.Reference                     `protobuf:"bytes,4,opt,name=preset" json:"preset,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *CommandChartApplyTheme) Reset()         { *m = CommandChartApplyTheme{} }
func (m *CommandChartApplyTheme) String() string { return proto.CompactTextString(m) }
func (*CommandChartApplyTheme) ProtoMessage()    {}

func (m *CommandChartApplyTheme) GetSuper() *TSS.ApplyThemeChildCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandChartApplyTheme) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *CommandChartApplyTheme) GetSwapCommand() *TSP.Reference {
	if m != nil {
		return m.SwapCommand
	}
	return nil
}

func (m *CommandChartApplyTheme) GetPreset() *TSP.Reference {
	if m != nil {
		return m.Preset
	}
	return nil
}

type CommandChartApplyPreset struct {
	Super            *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	SwapCommand      *TSP.Reference       `protobuf:"bytes,2,opt,name=swap_command" json:"swap_command,omitempty"`
	Preset           *TSP.Reference       `protobuf:"bytes,3,opt,name=preset" json:"preset,omitempty"`
	Behavior         *ApplyPresetBehavior `protobuf:"varint,4,opt,name=behavior,enum=ApplyPresetBehavior,def=1" json:"behavior,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *CommandChartApplyPreset) Reset()         { *m = CommandChartApplyPreset{} }
func (m *CommandChartApplyPreset) String() string { return proto.CompactTextString(m) }
func (*CommandChartApplyPreset) ProtoMessage()    {}

const Default_CommandChartApplyPreset_Behavior ApplyPresetBehavior = ApplyPresetBehavior_remove_overrides

func (m *CommandChartApplyPreset) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandChartApplyPreset) GetSwapCommand() *TSP.Reference {
	if m != nil {
		return m.SwapCommand
	}
	return nil
}

func (m *CommandChartApplyPreset) GetPreset() *TSP.Reference {
	if m != nil {
		return m.Preset
	}
	return nil
}

func (m *CommandChartApplyPreset) GetBehavior() ApplyPresetBehavior {
	if m != nil && m.Behavior != nil {
		return *m.Behavior
	}
	return Default_CommandChartApplyPreset_Behavior
}

type CommandCleanupGeometryArchive struct {
	Super                   *ChartCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	InfoGeometryCommand     *TSP.Reference       `protobuf:"bytes,2,opt,name=info_geometry_command" json:"info_geometry_command,omitempty"`
	AnchorAttachmentCommand *TSP.Reference       `protobuf:"bytes,3,opt,name=anchor_attachment_command" json:"anchor_attachment_command,omitempty"`
	OriginalLegendRect      *RectArchive   `protobuf:"bytes,4,opt,name=original_legend_rect" json:"original_legend_rect,omitempty"`
	XXX_unrecognized        []byte               `json:"-"`
}

func (m *CommandCleanupGeometryArchive) Reset()         { *m = CommandCleanupGeometryArchive{} }
func (m *CommandCleanupGeometryArchive) String() string { return proto.CompactTextString(m) }
func (*CommandCleanupGeometryArchive) ProtoMessage()    {}

func (m *CommandCleanupGeometryArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandCleanupGeometryArchive) GetInfoGeometryCommand() *TSP.Reference {
	if m != nil {
		return m.InfoGeometryCommand
	}
	return nil
}

func (m *CommandCleanupGeometryArchive) GetAnchorAttachmentCommand() *TSP.Reference {
	if m != nil {
		return m.AnchorAttachmentCommand
	}
	return nil
}

func (m *CommandCleanupGeometryArchive) GetOriginalLegendRect() *RectArchive {
	if m != nil {
		return m.OriginalLegendRect
	}
	return nil
}

type ChartCommandArchive struct {
	Super              *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info               *TSP.Reference      `protobuf:"bytes,2,req,name=info" json:"info,omitempty"`
	OriginalDirtyState *bool               `protobuf:"varint,3,opt,name=original_dirty_state" json:"original_dirty_state,omitempty"`
	XXX_unrecognized   []byte              `json:"-"`
}

func (m *ChartCommandArchive) Reset()         { *m = ChartCommandArchive{} }
func (m *ChartCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ChartCommandArchive) ProtoMessage()    {}

func (m *ChartCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ChartCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ChartCommandArchive) GetOriginalDirtyState() bool {
	if m != nil && m.OriginalDirtyState != nil {
		return *m.OriginalDirtyState
	}
	return false
}

type CommandReplaceGridValuesArchive struct {
	Super            *ChartCommandArchive                        `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Rowindex         *uint32                                     `protobuf:"varint,2,req,name=rowindex" json:"rowindex,omitempty"`
	Columnindex      *uint32                                     `protobuf:"varint,3,req,name=columnindex" json:"columnindex,omitempty"`
	OldDataRows      []*CommandReplaceGridValuesArchive_ValueRow `protobuf:"bytes,4,rep,name=old_data_rows" json:"old_data_rows,omitempty"`
	NewDataRows      []*CommandReplaceGridValuesArchive_ValueRow `protobuf:"bytes,5,rep,name=new_data_rows" json:"new_data_rows,omitempty"`
	OldRowNames      []string                                    `protobuf:"bytes,6,rep,name=old_row_names" json:"old_row_names,omitempty"`
	NewRowNames      []string                                    `protobuf:"bytes,7,rep,name=new_row_names" json:"new_row_names,omitempty"`
	OldColNames      []string                                    `protobuf:"bytes,8,rep,name=old_col_names" json:"old_col_names,omitempty"`
	NewColNames      []string                                    `protobuf:"bytes,9,rep,name=new_col_names" json:"new_col_names,omitempty"`
	RowsToAdd        *uint32                                     `protobuf:"varint,10,opt,name=rows_to_add" json:"rows_to_add,omitempty"`
	ColsToAdd        *uint32                                     `protobuf:"varint,11,opt,name=cols_to_add" json:"cols_to_add,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *CommandReplaceGridValuesArchive) Reset()         { *m = CommandReplaceGridValuesArchive{} }
func (m *CommandReplaceGridValuesArchive) String() string { return proto.CompactTextString(m) }
func (*CommandReplaceGridValuesArchive) ProtoMessage()    {}

func (m *CommandReplaceGridValuesArchive) GetSuper() *ChartCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetRowindex() uint32 {
	if m != nil && m.Rowindex != nil {
		return *m.Rowindex
	}
	return 0
}

func (m *CommandReplaceGridValuesArchive) GetColumnindex() uint32 {
	if m != nil && m.Columnindex != nil {
		return *m.Columnindex
	}
	return 0
}

func (m *CommandReplaceGridValuesArchive) GetOldDataRows() []*CommandReplaceGridValuesArchive_ValueRow {
	if m != nil {
		return m.OldDataRows
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetNewDataRows() []*CommandReplaceGridValuesArchive_ValueRow {
	if m != nil {
		return m.NewDataRows
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetOldRowNames() []string {
	if m != nil {
		return m.OldRowNames
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetNewRowNames() []string {
	if m != nil {
		return m.NewRowNames
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetOldColNames() []string {
	if m != nil {
		return m.OldColNames
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetNewColNames() []string {
	if m != nil {
		return m.NewColNames
	}
	return nil
}

func (m *CommandReplaceGridValuesArchive) GetRowsToAdd() uint32 {
	if m != nil && m.RowsToAdd != nil {
		return *m.RowsToAdd
	}
	return 0
}

func (m *CommandReplaceGridValuesArchive) GetColsToAdd() uint32 {
	if m != nil && m.ColsToAdd != nil {
		return *m.ColsToAdd
	}
	return 0
}

type CommandReplaceGridValuesArchive_ValueRow struct {
	Value            []float64 `protobuf:"fixed64,1,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CommandReplaceGridValuesArchive_ValueRow) Reset() {
	*m = CommandReplaceGridValuesArchive_ValueRow{}
}
func (m *CommandReplaceGridValuesArchive_ValueRow) String() string { return proto.CompactTextString(m) }
func (*CommandReplaceGridValuesArchive_ValueRow) ProtoMessage()    {}

func (m *CommandReplaceGridValuesArchive_ValueRow) GetValue() []float64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type CommandReplaceThemePresetArchive struct {
	Super            *TSK.CommandArchive                                        `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Theme            *TSP.Reference                                             `protobuf:"bytes,2,req,name=theme" json:"theme,omitempty"`
	OldPreset        *TSP.Reference                                             `protobuf:"bytes,3,opt,name=old_preset" json:"old_preset,omitempty"`
	NewPreset        *TSP.Reference                                             `protobuf:"bytes,4,opt,name=new_preset" json:"new_preset,omitempty"`
	Identifiers      []*CommandReplaceThemePresetArchive_StyleAndIdentifierPair `protobuf:"bytes,5,rep,name=identifiers" json:"identifiers,omitempty"`
	OldPresetIndex   *uint64                                                    `protobuf:"varint,6,opt,name=old_preset_index" json:"old_preset_index,omitempty"`
	XXX_unrecognized []byte                                                     `json:"-"`
}

func (m *CommandReplaceThemePresetArchive) Reset()         { *m = CommandReplaceThemePresetArchive{} }
func (m *CommandReplaceThemePresetArchive) String() string { return proto.CompactTextString(m) }
func (*CommandReplaceThemePresetArchive) ProtoMessage()    {}

func (m *CommandReplaceThemePresetArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommandReplaceThemePresetArchive) GetTheme() *TSP.Reference {
	if m != nil {
		return m.Theme
	}
	return nil
}

func (m *CommandReplaceThemePresetArchive) GetOldPreset() *TSP.Reference {
	if m != nil {
		return m.OldPreset
	}
	return nil
}

func (m *CommandReplaceThemePresetArchive) GetNewPreset() *TSP.Reference {
	if m != nil {
		return m.NewPreset
	}
	return nil
}

func (m *CommandReplaceThemePresetArchive) GetIdentifiers() []*CommandReplaceThemePresetArchive_StyleAndIdentifierPair {
	if m != nil {
		return m.Identifiers
	}
	return nil
}

func (m *CommandReplaceThemePresetArchive) GetOldPresetIndex() uint64 {
	if m != nil && m.OldPresetIndex != nil {
		return *m.OldPresetIndex
	}
	return 0
}

type CommandReplaceThemePresetArchive_StyleAndIdentifierPair struct {
	Style            *TSP.Reference `protobuf:"bytes,1,req,name=style" json:"style,omitempty"`
	Identifier       *string        `protobuf:"bytes,2,req,name=identifier" json:"identifier,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CommandReplaceThemePresetArchive_StyleAndIdentifierPair) Reset() {
	*m = CommandReplaceThemePresetArchive_StyleAndIdentifierPair{}
}
func (m *CommandReplaceThemePresetArchive_StyleAndIdentifierPair) String() string {
	return proto.CompactTextString(m)
}
func (*CommandReplaceThemePresetArchive_StyleAndIdentifierPair) ProtoMessage() {}

func (m *CommandReplaceThemePresetArchive_StyleAndIdentifierPair) GetStyle() *TSP.Reference {
	if m != nil {
		return m.Style
	}
	return nil
}

func (m *CommandReplaceThemePresetArchive_StyleAndIdentifierPair) GetIdentifier() string {
	if m != nil && m.Identifier != nil {
		return *m.Identifier
	}
	return ""
}

type CommandInvalidateWPCaches struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *CommandInvalidateWPCaches) Reset()         { *m = CommandInvalidateWPCaches{} }
func (m *CommandInvalidateWPCaches) String() string { return proto.CompactTextString(m) }
func (*CommandInvalidateWPCaches) ProtoMessage()    {}

func (m *CommandInvalidateWPCaches) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func init() {
	proto.RegisterEnum("StyleOwnerType", StyleOwnerType_name, StyleOwnerType_value)
	proto.RegisterEnum("StyleSwapType", StyleSwapType_name, StyleSwapType_value)
	proto.RegisterEnum("ApplyPresetBehavior", ApplyPresetBehavior_name, ApplyPresetBehavior_value)
}
