// Code generated by protoc-gen-go.
// source: TSDCommandArchives.proto
// DO NOT EDIT!

/*
Package TSD is a generated protocol buffer package.

It is generated from these files:
	TSDCommandArchives.proto

It has these top-level messages:
	ConnectionLineConnectCommandArchive
	GroupDrawablesCommandArchive
	UngroupGroupCommandArchive
	ContainerRemoveChildrenCommandArchive
	ContainerInsertChildrenCommandArchive
	ContainerReorderChildrenCommandArchive
	InfoGeometryCommandArchive
	DrawablePathSourceCommandArchive
	InstantAlphaCommandArchive
	DrawableShadowCommandArchive
	DrawableApplyThemeCommandArchive
	StyledInfoSetStyleCommandArchive
	ShapePathSourceFlipCommandArchive
	ShapeStyleSetValueCommandArchive
	ShapeApplyPresetCommandArchive
	ShapeSetLineEndCommandArchive
	MovieSetValueCommandArchive
	MediaStyleSetValueCommandArchive
	ImageMediaCommandArchive
	MediaOriginalSizeCommandArchive
	ImageMaskCommandArchive
	MediaApplyPresetCommandArchive
	ImageAdjustmentsCommandArchive
	MediaFlagsCommandArchive
	DrawablesCommandGroupArchive
	ExteriorTextWrapCommandArchive
	DrawableHyperlinkCommandArchive
	CommandSelectionBehaviorArchive
	ImageReplaceCommandArchive
	DrawableLockCommandArchive
	DrawableInfoCommentCommandArchive
	CommentStorageApplyCommandArchive
	GuideCommandArchive
	DrawableAspectRatioLockedCommandArchive
	DrawableAccessibilityDescriptionCommandArchive
	PasteStyleCommandArchive
*/
package TSD

import proto "github.com/golang/protobuf/proto"
import math "math"
import "github.com/dunhamsteve/iwork/proto/TSP"
import "github.com/dunhamsteve/iwork/proto/TSK"
import "github.com/dunhamsteve/iwork/proto/TSS"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type MovieSetValueCommandArchive_LoopOption int32

const (
	MovieSetValueCommandArchive_None         MovieSetValueCommandArchive_LoopOption = 0
	MovieSetValueCommandArchive_Repeat       MovieSetValueCommandArchive_LoopOption = 1
	MovieSetValueCommandArchive_BackAndForth MovieSetValueCommandArchive_LoopOption = 2
)

var MovieSetValueCommandArchive_LoopOption_name = map[int32]string{
	0: "None",
	1: "Repeat",
	2: "BackAndForth",
}
var MovieSetValueCommandArchive_LoopOption_value = map[string]int32{
	"None":         0,
	"Repeat":       1,
	"BackAndForth": 2,
}

func (x MovieSetValueCommandArchive_LoopOption) Enum() *MovieSetValueCommandArchive_LoopOption {
	p := new(MovieSetValueCommandArchive_LoopOption)
	*p = x
	return p
}
func (x MovieSetValueCommandArchive_LoopOption) String() string {
	return proto.EnumName(MovieSetValueCommandArchive_LoopOption_name, int32(x))
}
func (x *MovieSetValueCommandArchive_LoopOption) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MovieSetValueCommandArchive_LoopOption_value, data, "MovieSetValueCommandArchive_LoopOption")
	if err != nil {
		return err
	}
	*x = MovieSetValueCommandArchive_LoopOption(value)
	return nil
}

type DrawablesCommandGroupArchive_DrawablesCommandGroupType int32

const (
	DrawablesCommandGroupArchive_Constructive DrawablesCommandGroupArchive_DrawablesCommandGroupType = 1
	DrawablesCommandGroupArchive_Destructive  DrawablesCommandGroupArchive_DrawablesCommandGroupType = 2
	DrawablesCommandGroupArchive_InPlace      DrawablesCommandGroupArchive_DrawablesCommandGroupType = 3
)

var DrawablesCommandGroupArchive_DrawablesCommandGroupType_name = map[int32]string{
	1: "Constructive",
	2: "Destructive",
	3: "InPlace",
}
var DrawablesCommandGroupArchive_DrawablesCommandGroupType_value = map[string]int32{
	"Constructive": 1,
	"Destructive":  2,
	"InPlace":      3,
}

func (x DrawablesCommandGroupArchive_DrawablesCommandGroupType) Enum() *DrawablesCommandGroupArchive_DrawablesCommandGroupType {
	p := new(DrawablesCommandGroupArchive_DrawablesCommandGroupType)
	*p = x
	return p
}
func (x DrawablesCommandGroupArchive_DrawablesCommandGroupType) String() string {
	return proto.EnumName(DrawablesCommandGroupArchive_DrawablesCommandGroupType_name, int32(x))
}
func (x *DrawablesCommandGroupArchive_DrawablesCommandGroupType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DrawablesCommandGroupArchive_DrawablesCommandGroupType_value, data, "DrawablesCommandGroupArchive_DrawablesCommandGroupType")
	if err != nil {
		return err
	}
	*x = DrawablesCommandGroupArchive_DrawablesCommandGroupType(value)
	return nil
}

type CommandSelectionBehaviorArchive_CommandSelectionBehaviorType int32

const (
	CommandSelectionBehaviorArchive_Constructive CommandSelectionBehaviorArchive_CommandSelectionBehaviorType = 1
	CommandSelectionBehaviorArchive_Destructive  CommandSelectionBehaviorArchive_CommandSelectionBehaviorType = 2
	CommandSelectionBehaviorArchive_InPlace      CommandSelectionBehaviorArchive_CommandSelectionBehaviorType = 3
	CommandSelectionBehaviorArchive_Replace      CommandSelectionBehaviorArchive_CommandSelectionBehaviorType = 4
)

var CommandSelectionBehaviorArchive_CommandSelectionBehaviorType_name = map[int32]string{
	1: "Constructive",
	2: "Destructive",
	3: "InPlace",
	4: "Replace",
}
var CommandSelectionBehaviorArchive_CommandSelectionBehaviorType_value = map[string]int32{
	"Constructive": 1,
	"Destructive":  2,
	"InPlace":      3,
	"Replace":      4,
}

func (x CommandSelectionBehaviorArchive_CommandSelectionBehaviorType) Enum() *CommandSelectionBehaviorArchive_CommandSelectionBehaviorType {
	p := new(CommandSelectionBehaviorArchive_CommandSelectionBehaviorType)
	*p = x
	return p
}
func (x CommandSelectionBehaviorArchive_CommandSelectionBehaviorType) String() string {
	return proto.EnumName(CommandSelectionBehaviorArchive_CommandSelectionBehaviorType_name, int32(x))
}
func (x *CommandSelectionBehaviorArchive_CommandSelectionBehaviorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandSelectionBehaviorArchive_CommandSelectionBehaviorType_value, data, "CommandSelectionBehaviorArchive_CommandSelectionBehaviorType")
	if err != nil {
		return err
	}
	*x = CommandSelectionBehaviorArchive_CommandSelectionBehaviorType(value)
	return nil
}

type GuideCommandArchive_GuideCommandMode int32

const (
	GuideCommandArchive_Add     GuideCommandArchive_GuideCommandMode = 1
	GuideCommandArchive_Replace GuideCommandArchive_GuideCommandMode = 2
	GuideCommandArchive_Delete  GuideCommandArchive_GuideCommandMode = 3
)

var GuideCommandArchive_GuideCommandMode_name = map[int32]string{
	1: "Add",
	2: "Replace",
	3: "Delete",
}
var GuideCommandArchive_GuideCommandMode_value = map[string]int32{
	"Add":     1,
	"Replace": 2,
	"Delete":  3,
}

func (x GuideCommandArchive_GuideCommandMode) Enum() *GuideCommandArchive_GuideCommandMode {
	p := new(GuideCommandArchive_GuideCommandMode)
	*p = x
	return p
}
func (x GuideCommandArchive_GuideCommandMode) String() string {
	return proto.EnumName(GuideCommandArchive_GuideCommandMode_name, int32(x))
}
func (x *GuideCommandArchive_GuideCommandMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GuideCommandArchive_GuideCommandMode_value, data, "GuideCommandArchive_GuideCommandMode")
	if err != nil {
		return err
	}
	*x = GuideCommandArchive_GuideCommandMode(value)
	return nil
}

type ConnectionLineConnectCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ConnectionLine   *TSP.Reference      `protobuf:"bytes,2,req,name=connection_line" json:"connection_line,omitempty"`
	ConnectTo        *TSP.Reference      `protobuf:"bytes,3,opt,name=connect_to" json:"connect_to,omitempty"`
	ConnectFrom      *TSP.Reference      `protobuf:"bytes,4,opt,name=connect_from" json:"connect_from,omitempty"`
	OldConnectTo     *TSP.Reference      `protobuf:"bytes,5,opt,name=old_connect_to" json:"old_connect_to,omitempty"`
	OldConnectFrom   *TSP.Reference      `protobuf:"bytes,6,opt,name=old_connect_from" json:"old_connect_from,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ConnectionLineConnectCommandArchive) Reset()         { *m = ConnectionLineConnectCommandArchive{} }
func (m *ConnectionLineConnectCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ConnectionLineConnectCommandArchive) ProtoMessage()    {}

func (m *ConnectionLineConnectCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ConnectionLineConnectCommandArchive) GetConnectionLine() *TSP.Reference {
	if m != nil {
		return m.ConnectionLine
	}
	return nil
}

func (m *ConnectionLineConnectCommandArchive) GetConnectTo() *TSP.Reference {
	if m != nil {
		return m.ConnectTo
	}
	return nil
}

func (m *ConnectionLineConnectCommandArchive) GetConnectFrom() *TSP.Reference {
	if m != nil {
		return m.ConnectFrom
	}
	return nil
}

func (m *ConnectionLineConnectCommandArchive) GetOldConnectTo() *TSP.Reference {
	if m != nil {
		return m.OldConnectTo
	}
	return nil
}

func (m *ConnectionLineConnectCommandArchive) GetOldConnectFrom() *TSP.Reference {
	if m != nil {
		return m.OldConnectFrom
	}
	return nil
}

type GroupDrawablesCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Drawables        []*TSP.Reference    `protobuf:"bytes,2,rep,name=drawables" json:"drawables,omitempty"`
	Group            *TSP.Reference      `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GroupDrawablesCommandArchive) Reset()         { *m = GroupDrawablesCommandArchive{} }
func (m *GroupDrawablesCommandArchive) String() string { return proto.CompactTextString(m) }
func (*GroupDrawablesCommandArchive) ProtoMessage()    {}

func (m *GroupDrawablesCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *GroupDrawablesCommandArchive) GetDrawables() []*TSP.Reference {
	if m != nil {
		return m.Drawables
	}
	return nil
}

func (m *GroupDrawablesCommandArchive) GetGroup() *TSP.Reference {
	if m != nil {
		return m.Group
	}
	return nil
}

type UngroupGroupCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Drawables        []*TSP.Reference    `protobuf:"bytes,2,rep,name=drawables" json:"drawables,omitempty"`
	Group            *TSP.Reference      `protobuf:"bytes,3,opt,name=group" json:"group,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UngroupGroupCommandArchive) Reset()         { *m = UngroupGroupCommandArchive{} }
func (m *UngroupGroupCommandArchive) String() string { return proto.CompactTextString(m) }
func (*UngroupGroupCommandArchive) ProtoMessage()    {}

func (m *UngroupGroupCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *UngroupGroupCommandArchive) GetDrawables() []*TSP.Reference {
	if m != nil {
		return m.Drawables
	}
	return nil
}

func (m *UngroupGroupCommandArchive) GetGroup() *TSP.Reference {
	if m != nil {
		return m.Group
	}
	return nil
}

type ContainerRemoveChildrenCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Container        *TSP.Reference      `protobuf:"bytes,2,opt,name=container" json:"container,omitempty"`
	Children         []*TSP.Reference    `protobuf:"bytes,3,rep,name=children" json:"children,omitempty"`
	ChildrenIndices  *TSP.IndexSet       `protobuf:"bytes,4,opt,name=children_indices" json:"children_indices,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ContainerRemoveChildrenCommandArchive) Reset()         { *m = ContainerRemoveChildrenCommandArchive{} }
func (m *ContainerRemoveChildrenCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ContainerRemoveChildrenCommandArchive) ProtoMessage()    {}

func (m *ContainerRemoveChildrenCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ContainerRemoveChildrenCommandArchive) GetContainer() *TSP.Reference {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *ContainerRemoveChildrenCommandArchive) GetChildren() []*TSP.Reference {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *ContainerRemoveChildrenCommandArchive) GetChildrenIndices() *TSP.IndexSet {
	if m != nil {
		return m.ChildrenIndices
	}
	return nil
}

type ContainerInsertChildrenCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Container        *TSP.Reference      `protobuf:"bytes,2,opt,name=container" json:"container,omitempty"`
	Children         []*TSP.Reference    `protobuf:"bytes,3,rep,name=children" json:"children,omitempty"`
	Index            *uint64             `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ContainerInsertChildrenCommandArchive) Reset()         { *m = ContainerInsertChildrenCommandArchive{} }
func (m *ContainerInsertChildrenCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ContainerInsertChildrenCommandArchive) ProtoMessage()    {}

func (m *ContainerInsertChildrenCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ContainerInsertChildrenCommandArchive) GetContainer() *TSP.Reference {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *ContainerInsertChildrenCommandArchive) GetChildren() []*TSP.Reference {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *ContainerInsertChildrenCommandArchive) GetIndex() uint64 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

type ContainerReorderChildrenCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Container        *TSP.Reference      `protobuf:"bytes,2,opt,name=container" json:"container,omitempty"`
	Children         []*TSP.Reference    `protobuf:"bytes,3,rep,name=children" json:"children,omitempty"`
	ChildrenIndices  *TSP.IndexSet       `protobuf:"bytes,4,opt,name=children_indices" json:"children_indices,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ContainerReorderChildrenCommandArchive) Reset() {
	*m = ContainerReorderChildrenCommandArchive{}
}
func (m *ContainerReorderChildrenCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ContainerReorderChildrenCommandArchive) ProtoMessage()    {}

func (m *ContainerReorderChildrenCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ContainerReorderChildrenCommandArchive) GetContainer() *TSP.Reference {
	if m != nil {
		return m.Container
	}
	return nil
}

func (m *ContainerReorderChildrenCommandArchive) GetChildren() []*TSP.Reference {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *ContainerReorderChildrenCommandArchive) GetChildrenIndices() *TSP.IndexSet {
	if m != nil {
		return m.ChildrenIndices
	}
	return nil
}

type InfoGeometryCommandArchive struct {
	Super                             *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info                              *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	NewGeometry                       *GeometryArchive    `protobuf:"bytes,3,opt,name=newGeometry" json:"newGeometry,omitempty"`
	OldGeometry                       *GeometryArchive    `protobuf:"bytes,4,opt,name=oldGeometry" json:"oldGeometry,omitempty"`
	ShouldClearObjectPlaceholderFlag  *bool               `protobuf:"varint,5,opt,name=shouldClearObjectPlaceholderFlag" json:"shouldClearObjectPlaceholderFlag,omitempty"`
	DidMatchObjectPlaceholderGeometry *bool               `protobuf:"varint,6,opt,name=didMatchObjectPlaceholderGeometry" json:"didMatchObjectPlaceholderGeometry,omitempty"`
	XXX_unrecognized                  []byte              `json:"-"`
}

func (m *InfoGeometryCommandArchive) Reset()         { *m = InfoGeometryCommandArchive{} }
func (m *InfoGeometryCommandArchive) String() string { return proto.CompactTextString(m) }
func (*InfoGeometryCommandArchive) ProtoMessage()    {}

func (m *InfoGeometryCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *InfoGeometryCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *InfoGeometryCommandArchive) GetNewGeometry() *GeometryArchive {
	if m != nil {
		return m.NewGeometry
	}
	return nil
}

func (m *InfoGeometryCommandArchive) GetOldGeometry() *GeometryArchive {
	if m != nil {
		return m.OldGeometry
	}
	return nil
}

func (m *InfoGeometryCommandArchive) GetShouldClearObjectPlaceholderFlag() bool {
	if m != nil && m.ShouldClearObjectPlaceholderFlag != nil {
		return *m.ShouldClearObjectPlaceholderFlag
	}
	return false
}

func (m *InfoGeometryCommandArchive) GetDidMatchObjectPlaceholderGeometry() bool {
	if m != nil && m.DidMatchObjectPlaceholderGeometry != nil {
		return *m.DidMatchObjectPlaceholderGeometry
	}
	return false
}

type DrawablePathSourceCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Oldpathsource    *PathSourceArchive  `protobuf:"bytes,3,opt,name=oldpathsource" json:"oldpathsource,omitempty"`
	Newpathsource    *PathSourceArchive  `protobuf:"bytes,4,opt,name=newpathsource" json:"newpathsource,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *DrawablePathSourceCommandArchive) Reset()         { *m = DrawablePathSourceCommandArchive{} }
func (m *DrawablePathSourceCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawablePathSourceCommandArchive) ProtoMessage()    {}

func (m *DrawablePathSourceCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawablePathSourceCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawablePathSourceCommandArchive) GetOldpathsource() *PathSourceArchive {
	if m != nil {
		return m.Oldpathsource
	}
	return nil
}

func (m *DrawablePathSourceCommandArchive) GetNewpathsource() *PathSourceArchive {
	if m != nil {
		return m.Newpathsource
	}
	return nil
}

type InstantAlphaCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Image            *TSP.Reference      `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	Oldpath          *TSP.Path           `protobuf:"bytes,3,opt,name=oldpath" json:"oldpath,omitempty"`
	Newpath          *TSP.Path           `protobuf:"bytes,4,opt,name=newpath" json:"newpath,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *InstantAlphaCommandArchive) Reset()         { *m = InstantAlphaCommandArchive{} }
func (m *InstantAlphaCommandArchive) String() string { return proto.CompactTextString(m) }
func (*InstantAlphaCommandArchive) ProtoMessage()    {}

func (m *InstantAlphaCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *InstantAlphaCommandArchive) GetImage() *TSP.Reference {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *InstantAlphaCommandArchive) GetOldpath() *TSP.Path {
	if m != nil {
		return m.Oldpath
	}
	return nil
}

func (m *InstantAlphaCommandArchive) GetNewpath() *TSP.Path {
	if m != nil {
		return m.Newpath
	}
	return nil
}

type DrawableShadowCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Oldshadow        *ShadowArchive      `protobuf:"bytes,3,opt,name=oldshadow" json:"oldshadow,omitempty"`
	Newshadow        *ShadowArchive      `protobuf:"bytes,4,opt,name=newshadow" json:"newshadow,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *DrawableShadowCommandArchive) Reset()         { *m = DrawableShadowCommandArchive{} }
func (m *DrawableShadowCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawableShadowCommandArchive) ProtoMessage()    {}

func (m *DrawableShadowCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableShadowCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableShadowCommandArchive) GetOldshadow() *ShadowArchive {
	if m != nil {
		return m.Oldshadow
	}
	return nil
}

func (m *DrawableShadowCommandArchive) GetNewshadow() *ShadowArchive {
	if m != nil {
		return m.Newshadow
	}
	return nil
}

type DrawableApplyThemeCommandArchive struct {
	Super            *TSS.ApplyThemeChildCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference                     `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Style            *TSP.Reference                     `protobuf:"bytes,3,opt,name=style" json:"style,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *DrawableApplyThemeCommandArchive) Reset()         { *m = DrawableApplyThemeCommandArchive{} }
func (m *DrawableApplyThemeCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawableApplyThemeCommandArchive) ProtoMessage()    {}

func (m *DrawableApplyThemeCommandArchive) GetSuper() *TSS.ApplyThemeChildCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableApplyThemeCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableApplyThemeCommandArchive) GetStyle() *TSP.Reference {
	if m != nil {
		return m.Style
	}
	return nil
}

type StyledInfoSetStyleCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Style            *TSP.Reference      `protobuf:"bytes,3,opt,name=style" json:"style,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *StyledInfoSetStyleCommandArchive) Reset()         { *m = StyledInfoSetStyleCommandArchive{} }
func (m *StyledInfoSetStyleCommandArchive) String() string { return proto.CompactTextString(m) }
func (*StyledInfoSetStyleCommandArchive) ProtoMessage()    {}

func (m *StyledInfoSetStyleCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *StyledInfoSetStyleCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *StyledInfoSetStyleCommandArchive) GetStyle() *TSP.Reference {
	if m != nil {
		return m.Style
	}
	return nil
}

type ShapePathSourceFlipCommandArchive struct {
	Super             *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info              *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	NewHorizontalFlip *bool               `protobuf:"varint,3,opt,name=newHorizontalFlip" json:"newHorizontalFlip,omitempty"`
	NewVerticalFlip   *bool               `protobuf:"varint,4,opt,name=newVerticalFlip" json:"newVerticalFlip,omitempty"`
	OldHorizontalFlip *bool               `protobuf:"varint,5,opt,name=oldHorizontalFlip" json:"oldHorizontalFlip,omitempty"`
	OldVerticalFlip   *bool               `protobuf:"varint,6,opt,name=oldVerticalFlip" json:"oldVerticalFlip,omitempty"`
	XXX_unrecognized  []byte              `json:"-"`
}

func (m *ShapePathSourceFlipCommandArchive) Reset()         { *m = ShapePathSourceFlipCommandArchive{} }
func (m *ShapePathSourceFlipCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ShapePathSourceFlipCommandArchive) ProtoMessage()    {}

func (m *ShapePathSourceFlipCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ShapePathSourceFlipCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ShapePathSourceFlipCommandArchive) GetNewHorizontalFlip() bool {
	if m != nil && m.NewHorizontalFlip != nil {
		return *m.NewHorizontalFlip
	}
	return false
}

func (m *ShapePathSourceFlipCommandArchive) GetNewVerticalFlip() bool {
	if m != nil && m.NewVerticalFlip != nil {
		return *m.NewVerticalFlip
	}
	return false
}

func (m *ShapePathSourceFlipCommandArchive) GetOldHorizontalFlip() bool {
	if m != nil && m.OldHorizontalFlip != nil {
		return *m.OldHorizontalFlip
	}
	return false
}

func (m *ShapePathSourceFlipCommandArchive) GetOldVerticalFlip() bool {
	if m != nil && m.OldVerticalFlip != nil {
		return *m.OldVerticalFlip
	}
	return false
}

type ShapeStyleSetValueCommandArchive struct {
	Super            *StyledInfoSetStyleCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ShapeProperties  *ShapeStylePropertiesArchive      `protobuf:"bytes,4,opt,name=shape_properties" json:"shape_properties,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *ShapeStyleSetValueCommandArchive) Reset()         { *m = ShapeStyleSetValueCommandArchive{} }
func (m *ShapeStyleSetValueCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ShapeStyleSetValueCommandArchive) ProtoMessage()    {}

func (m *ShapeStyleSetValueCommandArchive) GetSuper() *StyledInfoSetStyleCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ShapeStyleSetValueCommandArchive) GetShapeProperties() *ShapeStylePropertiesArchive {
	if m != nil {
		return m.ShapeProperties
	}
	return nil
}

type ShapeApplyPresetCommandArchive struct {
	Super            *StyledInfoSetStyleCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Stylepreset      *TSP.Reference                    `protobuf:"bytes,10,opt,name=stylepreset" json:"stylepreset,omitempty"`
	Colorpreset      *TSP.Color                        `protobuf:"bytes,11,opt,name=colorpreset" json:"colorpreset,omitempty"`
	Fillpreset       *FillArchive                      `protobuf:"bytes,12,opt,name=fillpreset" json:"fillpreset,omitempty"`
	Shadowpreset     *ShadowArchive                    `protobuf:"bytes,13,opt,name=shadowpreset" json:"shadowpreset,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *ShapeApplyPresetCommandArchive) Reset()         { *m = ShapeApplyPresetCommandArchive{} }
func (m *ShapeApplyPresetCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ShapeApplyPresetCommandArchive) ProtoMessage()    {}

func (m *ShapeApplyPresetCommandArchive) GetSuper() *StyledInfoSetStyleCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ShapeApplyPresetCommandArchive) GetStylepreset() *TSP.Reference {
	if m != nil {
		return m.Stylepreset
	}
	return nil
}

func (m *ShapeApplyPresetCommandArchive) GetColorpreset() *TSP.Color {
	if m != nil {
		return m.Colorpreset
	}
	return nil
}

func (m *ShapeApplyPresetCommandArchive) GetFillpreset() *FillArchive {
	if m != nil {
		return m.Fillpreset
	}
	return nil
}

func (m *ShapeApplyPresetCommandArchive) GetShadowpreset() *ShadowArchive {
	if m != nil {
		return m.Shadowpreset
	}
	return nil
}

type ShapeSetLineEndCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Shape            *TSP.Reference      `protobuf:"bytes,2,opt,name=shape" json:"shape,omitempty"`
	LineEnd          *LineEndArchive     `protobuf:"bytes,3,opt,name=line_end" json:"line_end,omitempty"`
	IsHeadLineEnd    *bool               `protobuf:"varint,4,opt,name=is_head_line_end" json:"is_head_line_end,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ShapeSetLineEndCommandArchive) Reset()         { *m = ShapeSetLineEndCommandArchive{} }
func (m *ShapeSetLineEndCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ShapeSetLineEndCommandArchive) ProtoMessage()    {}

func (m *ShapeSetLineEndCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ShapeSetLineEndCommandArchive) GetShape() *TSP.Reference {
	if m != nil {
		return m.Shape
	}
	return nil
}

func (m *ShapeSetLineEndCommandArchive) GetLineEnd() *LineEndArchive {
	if m != nil {
		return m.LineEnd
	}
	return nil
}

func (m *ShapeSetLineEndCommandArchive) GetIsHeadLineEnd() bool {
	if m != nil && m.IsHeadLineEnd != nil {
		return *m.IsHeadLineEnd
	}
	return false
}

type MovieSetValueCommandArchive struct {
	Super              *TSK.CommandArchive                        `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Movie              *TSP.Reference                             `protobuf:"bytes,2,opt,name=movie" json:"movie,omitempty"`
	DeprecatedProperty *string                                    `protobuf:"bytes,3,opt,name=deprecated_property" json:"deprecated_property,omitempty"`
	Property           *int32                                     `protobuf:"varint,4,opt,name=property" json:"property,omitempty"`
	Value              *MovieSetValueCommandArchive_PropertyValue `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized   []byte                                     `json:"-"`
}

func (m *MovieSetValueCommandArchive) Reset()         { *m = MovieSetValueCommandArchive{} }
func (m *MovieSetValueCommandArchive) String() string { return proto.CompactTextString(m) }
func (*MovieSetValueCommandArchive) ProtoMessage()    {}

func (m *MovieSetValueCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *MovieSetValueCommandArchive) GetMovie() *TSP.Reference {
	if m != nil {
		return m.Movie
	}
	return nil
}

func (m *MovieSetValueCommandArchive) GetDeprecatedProperty() string {
	if m != nil && m.DeprecatedProperty != nil {
		return *m.DeprecatedProperty
	}
	return ""
}

func (m *MovieSetValueCommandArchive) GetProperty() int32 {
	if m != nil && m.Property != nil {
		return *m.Property
	}
	return 0
}

func (m *MovieSetValueCommandArchive) GetValue() *MovieSetValueCommandArchive_PropertyValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type MovieSetValueCommandArchive_PropertyValue struct {
	Starttime              *float64                                `protobuf:"fixed64,1,opt,name=starttime" json:"starttime,omitempty"`
	Endtime                *float64                                `protobuf:"fixed64,2,opt,name=endtime" json:"endtime,omitempty"`
	Postertime             *float64                                `protobuf:"fixed64,3,opt,name=postertime" json:"postertime,omitempty"`
	Posterimagedata        *TSP.DataReference                      `protobuf:"bytes,4,opt,name=posterimagedata" json:"posterimagedata,omitempty"`
	Autoplay               *bool                                   `protobuf:"varint,5,opt,name=autoplay" json:"autoplay,omitempty"`
	LoopOption             *MovieSetValueCommandArchive_LoopOption `protobuf:"varint,6,opt,name=loopOption,enum=MovieSetValueCommandArchive_LoopOption" json:"loopOption,omitempty"`
	Volume                 *float32                                `protobuf:"fixed32,7,opt,name=volume" json:"volume,omitempty"`
	Media                  *TSP.DataReference                      `protobuf:"bytes,8,opt,name=media" json:"media,omitempty"`
	Importedauxiliarymedia *TSP.DataReference                      `protobuf:"bytes,9,opt,name=importedauxiliarymedia" json:"importedauxiliarymedia,omitempty"`
	XXX_unrecognized       []byte                                  `json:"-"`
}

func (m *MovieSetValueCommandArchive_PropertyValue) Reset() {
	*m = MovieSetValueCommandArchive_PropertyValue{}
}
func (m *MovieSetValueCommandArchive_PropertyValue) String() string { return proto.CompactTextString(m) }
func (*MovieSetValueCommandArchive_PropertyValue) ProtoMessage()    {}

func (m *MovieSetValueCommandArchive_PropertyValue) GetStarttime() float64 {
	if m != nil && m.Starttime != nil {
		return *m.Starttime
	}
	return 0
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetEndtime() float64 {
	if m != nil && m.Endtime != nil {
		return *m.Endtime
	}
	return 0
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetPostertime() float64 {
	if m != nil && m.Postertime != nil {
		return *m.Postertime
	}
	return 0
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetPosterimagedata() *TSP.DataReference {
	if m != nil {
		return m.Posterimagedata
	}
	return nil
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetAutoplay() bool {
	if m != nil && m.Autoplay != nil {
		return *m.Autoplay
	}
	return false
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetLoopOption() MovieSetValueCommandArchive_LoopOption {
	if m != nil && m.LoopOption != nil {
		return *m.LoopOption
	}
	return MovieSetValueCommandArchive_None
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetVolume() float32 {
	if m != nil && m.Volume != nil {
		return *m.Volume
	}
	return 0
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetMedia() *TSP.DataReference {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *MovieSetValueCommandArchive_PropertyValue) GetImportedauxiliarymedia() *TSP.DataReference {
	if m != nil {
		return m.Importedauxiliarymedia
	}
	return nil
}

type MediaStyleSetValueCommandArchive struct {
	Super            *StyledInfoSetStyleCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	MediaProperties  *MediaStylePropertiesArchive      `protobuf:"bytes,4,opt,name=media_properties" json:"media_properties,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *MediaStyleSetValueCommandArchive) Reset()         { *m = MediaStyleSetValueCommandArchive{} }
func (m *MediaStyleSetValueCommandArchive) String() string { return proto.CompactTextString(m) }
func (*MediaStyleSetValueCommandArchive) ProtoMessage()    {}

func (m *MediaStyleSetValueCommandArchive) GetSuper() *StyledInfoSetStyleCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *MediaStyleSetValueCommandArchive) GetMediaProperties() *MediaStylePropertiesArchive {
	if m != nil {
		return m.MediaProperties
	}
	return nil
}

type ImageMediaCommandArchive struct {
	Super                        *TSK.CommandArchive      `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info                         *TSP.Reference           `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	NewImageData                 *TSP.DataReference       `protobuf:"bytes,8,opt,name=newImageData" json:"newImageData,omitempty"`
	OldImageData                 *TSP.DataReference       `protobuf:"bytes,9,opt,name=oldImageData" json:"oldImageData,omitempty"`
	OldOriginalImageData         *TSP.DataReference       `protobuf:"bytes,10,opt,name=oldOriginalImageData" json:"oldOriginalImageData,omitempty"`
	OldNaturalSize               *TSP.Size                `protobuf:"bytes,6,opt,name=oldNaturalSize" json:"oldNaturalSize,omitempty"`
	NewOriginalImageData         *TSP.DataReference       `protobuf:"bytes,11,opt,name=newOriginalImageData" json:"newOriginalImageData,omitempty"`
	OldImageAdjustments          *ImageAdjustmentsArchive `protobuf:"bytes,12,opt,name=oldImageAdjustments" json:"oldImageAdjustments,omitempty"`
	OldAdjustedImageData         *TSP.DataReference       `protobuf:"bytes,13,opt,name=oldAdjustedImageData" json:"oldAdjustedImageData,omitempty"`
	OldEnhancedImageData         *TSP.DataReference       `protobuf:"bytes,14,opt,name=oldEnhancedImageData" json:"oldEnhancedImageData,omitempty"`
	DatabaseNewImageData         *TSP.Reference           `protobuf:"bytes,3,opt,name=database_newImageData" json:"database_newImageData,omitempty"`
	DatabaseOldImageData         *TSP.Reference           `protobuf:"bytes,4,opt,name=database_oldImageData" json:"database_oldImageData,omitempty"`
	DatabaseOldOriginalImageData *TSP.Reference           `protobuf:"bytes,5,opt,name=database_oldOriginalImageData" json:"database_oldOriginalImageData,omitempty"`
	DatabaseNewOriginalImageData *TSP.Reference           `protobuf:"bytes,7,opt,name=database_newOriginalImageData" json:"database_newOriginalImageData,omitempty"`
	XXX_unrecognized             []byte                   `json:"-"`
}

func (m *ImageMediaCommandArchive) Reset()         { *m = ImageMediaCommandArchive{} }
func (m *ImageMediaCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ImageMediaCommandArchive) ProtoMessage()    {}

func (m *ImageMediaCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetNewImageData() *TSP.DataReference {
	if m != nil {
		return m.NewImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetOldImageData() *TSP.DataReference {
	if m != nil {
		return m.OldImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetOldOriginalImageData() *TSP.DataReference {
	if m != nil {
		return m.OldOriginalImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetOldNaturalSize() *TSP.Size {
	if m != nil {
		return m.OldNaturalSize
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetNewOriginalImageData() *TSP.DataReference {
	if m != nil {
		return m.NewOriginalImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetOldImageAdjustments() *ImageAdjustmentsArchive {
	if m != nil {
		return m.OldImageAdjustments
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetOldAdjustedImageData() *TSP.DataReference {
	if m != nil {
		return m.OldAdjustedImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetOldEnhancedImageData() *TSP.DataReference {
	if m != nil {
		return m.OldEnhancedImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetDatabaseNewImageData() *TSP.Reference {
	if m != nil {
		return m.DatabaseNewImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetDatabaseOldImageData() *TSP.Reference {
	if m != nil {
		return m.DatabaseOldImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetDatabaseOldOriginalImageData() *TSP.Reference {
	if m != nil {
		return m.DatabaseOldOriginalImageData
	}
	return nil
}

func (m *ImageMediaCommandArchive) GetDatabaseNewOriginalImageData() *TSP.Reference {
	if m != nil {
		return m.DatabaseNewOriginalImageData
	}
	return nil
}

type MediaOriginalSizeCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	NewOriginalSize  *TSP.Size           `protobuf:"bytes,3,opt,name=newOriginalSize" json:"newOriginalSize,omitempty"`
	OldOriginalSize  *TSP.Size           `protobuf:"bytes,4,opt,name=oldOriginalSize" json:"oldOriginalSize,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MediaOriginalSizeCommandArchive) Reset()         { *m = MediaOriginalSizeCommandArchive{} }
func (m *MediaOriginalSizeCommandArchive) String() string { return proto.CompactTextString(m) }
func (*MediaOriginalSizeCommandArchive) ProtoMessage()    {}

func (m *MediaOriginalSizeCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *MediaOriginalSizeCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MediaOriginalSizeCommandArchive) GetNewOriginalSize() *TSP.Size {
	if m != nil {
		return m.NewOriginalSize
	}
	return nil
}

func (m *MediaOriginalSizeCommandArchive) GetOldOriginalSize() *TSP.Size {
	if m != nil {
		return m.OldOriginalSize
	}
	return nil
}

type ImageMaskCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	NewMaskInfo      *TSP.Reference      `protobuf:"bytes,3,opt,name=newMaskInfo" json:"newMaskInfo,omitempty"`
	OldMaskInfo      *TSP.Reference      `protobuf:"bytes,4,opt,name=oldMaskInfo" json:"oldMaskInfo,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ImageMaskCommandArchive) Reset()         { *m = ImageMaskCommandArchive{} }
func (m *ImageMaskCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ImageMaskCommandArchive) ProtoMessage()    {}

func (m *ImageMaskCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ImageMaskCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ImageMaskCommandArchive) GetNewMaskInfo() *TSP.Reference {
	if m != nil {
		return m.NewMaskInfo
	}
	return nil
}

func (m *ImageMaskCommandArchive) GetOldMaskInfo() *TSP.Reference {
	if m != nil {
		return m.OldMaskInfo
	}
	return nil
}

type MediaApplyPresetCommandArchive struct {
	Super            *StyledInfoSetStyleCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Stylepreset      *TSP.Reference                    `protobuf:"bytes,10,opt,name=stylepreset" json:"stylepreset,omitempty"`
	Shadowpreset     *ShadowArchive                    `protobuf:"bytes,11,opt,name=shadowpreset" json:"shadowpreset,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (m *MediaApplyPresetCommandArchive) Reset()         { *m = MediaApplyPresetCommandArchive{} }
func (m *MediaApplyPresetCommandArchive) String() string { return proto.CompactTextString(m) }
func (*MediaApplyPresetCommandArchive) ProtoMessage()    {}

func (m *MediaApplyPresetCommandArchive) GetSuper() *StyledInfoSetStyleCommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *MediaApplyPresetCommandArchive) GetStylepreset() *TSP.Reference {
	if m != nil {
		return m.Stylepreset
	}
	return nil
}

func (m *MediaApplyPresetCommandArchive) GetShadowpreset() *ShadowArchive {
	if m != nil {
		return m.Shadowpreset
	}
	return nil
}

type ImageAdjustmentsCommandArchive struct {
	Super                     *TSK.CommandArchive      `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OldImageAdjustments       *ImageAdjustmentsArchive `protobuf:"bytes,2,opt,name=old_image_adjustments" json:"old_image_adjustments,omitempty"`
	NewImageAdjustments       *ImageAdjustmentsArchive `protobuf:"bytes,3,opt,name=new_image_adjustments" json:"new_image_adjustments,omitempty"`
	AdjustedImageData         *TSP.DataReference       `protobuf:"bytes,4,opt,name=adjustedImageData" json:"adjustedImageData,omitempty"`
	ReplacedAdjustedImageData *TSP.DataReference       `protobuf:"bytes,5,opt,name=replacedAdjustedImageData" json:"replacedAdjustedImageData,omitempty"`
	EnhancedImageData         *TSP.DataReference       `protobuf:"bytes,6,opt,name=enhancedImageData" json:"enhancedImageData,omitempty"`
	ReplacedEnhancedImageData *TSP.DataReference       `protobuf:"bytes,7,opt,name=replacedEnhancedImageData" json:"replacedEnhancedImageData,omitempty"`
	XXX_unrecognized          []byte                   `json:"-"`
}

func (m *ImageAdjustmentsCommandArchive) Reset()         { *m = ImageAdjustmentsCommandArchive{} }
func (m *ImageAdjustmentsCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ImageAdjustmentsCommandArchive) ProtoMessage()    {}

func (m *ImageAdjustmentsCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ImageAdjustmentsCommandArchive) GetOldImageAdjustments() *ImageAdjustmentsArchive {
	if m != nil {
		return m.OldImageAdjustments
	}
	return nil
}

func (m *ImageAdjustmentsCommandArchive) GetNewImageAdjustments() *ImageAdjustmentsArchive {
	if m != nil {
		return m.NewImageAdjustments
	}
	return nil
}

func (m *ImageAdjustmentsCommandArchive) GetAdjustedImageData() *TSP.DataReference {
	if m != nil {
		return m.AdjustedImageData
	}
	return nil
}

func (m *ImageAdjustmentsCommandArchive) GetReplacedAdjustedImageData() *TSP.DataReference {
	if m != nil {
		return m.ReplacedAdjustedImageData
	}
	return nil
}

func (m *ImageAdjustmentsCommandArchive) GetEnhancedImageData() *TSP.DataReference {
	if m != nil {
		return m.EnhancedImageData
	}
	return nil
}

func (m *ImageAdjustmentsCommandArchive) GetReplacedEnhancedImageData() *TSP.DataReference {
	if m != nil {
		return m.ReplacedEnhancedImageData
	}
	return nil
}

type MediaFlagsCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Flags            *uint32             `protobuf:"varint,3,opt,name=flags" json:"flags,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MediaFlagsCommandArchive) Reset()         { *m = MediaFlagsCommandArchive{} }
func (m *MediaFlagsCommandArchive) String() string { return proto.CompactTextString(m) }
func (*MediaFlagsCommandArchive) ProtoMessage()    {}

func (m *MediaFlagsCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *MediaFlagsCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MediaFlagsCommandArchive) GetFlags() uint32 {
	if m != nil && m.Flags != nil {
		return *m.Flags
	}
	return 0
}

type DrawablesCommandGroupArchive struct {
	Super             *TSK.CommandGroupArchive                                `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	ObsoleteSelection *CanvasSelectionArchive                                 `protobuf:"bytes,2,opt,name=obsolete_selection" json:"obsolete_selection,omitempty"`
	Modelforselection *TSP.Reference                                          `protobuf:"bytes,3,opt,name=modelforselection" json:"modelforselection,omitempty"`
	Type              *DrawablesCommandGroupArchive_DrawablesCommandGroupType `protobuf:"varint,4,opt,name=type,enum=DrawablesCommandGroupArchive_DrawablesCommandGroupType" json:"type,omitempty"`
	ForDrag           *bool                                                   `protobuf:"varint,5,opt,name=forDrag" json:"forDrag,omitempty"`
	Archivedselection *TSP.Reference                                          `protobuf:"bytes,6,opt,name=archivedselection" json:"archivedselection,omitempty"`
	XXX_unrecognized  []byte                                                  `json:"-"`
}

func (m *DrawablesCommandGroupArchive) Reset()         { *m = DrawablesCommandGroupArchive{} }
func (m *DrawablesCommandGroupArchive) String() string { return proto.CompactTextString(m) }
func (*DrawablesCommandGroupArchive) ProtoMessage()    {}

func (m *DrawablesCommandGroupArchive) GetSuper() *TSK.CommandGroupArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawablesCommandGroupArchive) GetObsoleteSelection() *CanvasSelectionArchive {
	if m != nil {
		return m.ObsoleteSelection
	}
	return nil
}

func (m *DrawablesCommandGroupArchive) GetModelforselection() *TSP.Reference {
	if m != nil {
		return m.Modelforselection
	}
	return nil
}

func (m *DrawablesCommandGroupArchive) GetType() DrawablesCommandGroupArchive_DrawablesCommandGroupType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return DrawablesCommandGroupArchive_Constructive
}

func (m *DrawablesCommandGroupArchive) GetForDrag() bool {
	if m != nil && m.ForDrag != nil {
		return *m.ForDrag
	}
	return false
}

func (m *DrawablesCommandGroupArchive) GetArchivedselection() *TSP.Reference {
	if m != nil {
		return m.Archivedselection
	}
	return nil
}

type ExteriorTextWrapCommandArchive struct {
	Super            *TSK.CommandArchive                           `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	InfoAndWrap      []*ExteriorTextWrapCommandArchive_InfoAndWrap `protobuf:"bytes,2,rep,name=info_and_wrap" json:"info_and_wrap,omitempty"`
	XXX_unrecognized []byte                                        `json:"-"`
}

func (m *ExteriorTextWrapCommandArchive) Reset()         { *m = ExteriorTextWrapCommandArchive{} }
func (m *ExteriorTextWrapCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ExteriorTextWrapCommandArchive) ProtoMessage()    {}

func (m *ExteriorTextWrapCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *ExteriorTextWrapCommandArchive) GetInfoAndWrap() []*ExteriorTextWrapCommandArchive_InfoAndWrap {
	if m != nil {
		return m.InfoAndWrap
	}
	return nil
}

type ExteriorTextWrapCommandArchive_InfoAndWrap struct {
	Info             *TSP.Reference           `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	ExteriorTextWrap *ExteriorTextWrapArchive `protobuf:"bytes,2,opt,name=exterior_text_wrap" json:"exterior_text_wrap,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ExteriorTextWrapCommandArchive_InfoAndWrap) Reset() {
	*m = ExteriorTextWrapCommandArchive_InfoAndWrap{}
}
func (m *ExteriorTextWrapCommandArchive_InfoAndWrap) String() string {
	return proto.CompactTextString(m)
}
func (*ExteriorTextWrapCommandArchive_InfoAndWrap) ProtoMessage() {}

func (m *ExteriorTextWrapCommandArchive_InfoAndWrap) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ExteriorTextWrapCommandArchive_InfoAndWrap) GetExteriorTextWrap() *ExteriorTextWrapArchive {
	if m != nil {
		return m.ExteriorTextWrap
	}
	return nil
}

type DrawableHyperlinkCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	OldhyperlinkUrl  *string             `protobuf:"bytes,3,opt,name=oldhyperlink_url" json:"oldhyperlink_url,omitempty"`
	NewhyperlinkUrl  *string             `protobuf:"bytes,4,opt,name=newhyperlink_url" json:"newhyperlink_url,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *DrawableHyperlinkCommandArchive) Reset()         { *m = DrawableHyperlinkCommandArchive{} }
func (m *DrawableHyperlinkCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawableHyperlinkCommandArchive) ProtoMessage()    {}

func (m *DrawableHyperlinkCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableHyperlinkCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableHyperlinkCommandArchive) GetOldhyperlinkUrl() string {
	if m != nil && m.OldhyperlinkUrl != nil {
		return *m.OldhyperlinkUrl
	}
	return ""
}

func (m *DrawableHyperlinkCommandArchive) GetNewhyperlinkUrl() string {
	if m != nil && m.NewhyperlinkUrl != nil {
		return *m.NewhyperlinkUrl
	}
	return ""
}

type CommandSelectionBehaviorArchive struct {
	ModelForSelection    *TSP.Reference                                                `protobuf:"bytes,2,opt,name=model_for_selection" json:"model_for_selection,omitempty"`
	Type                 *CommandSelectionBehaviorArchive_CommandSelectionBehaviorType `protobuf:"varint,3,opt,name=type,enum=CommandSelectionBehaviorArchive_CommandSelectionBehaviorType" json:"type,omitempty"`
	ArchivedSelection    *TSP.Reference                                                `protobuf:"bytes,4,opt,name=archived_selection" json:"archived_selection,omitempty"`
	ArchivedNewSelection *TSP.Reference                                                `protobuf:"bytes,5,opt,name=archived_new_selection" json:"archived_new_selection,omitempty"`
	XXX_unrecognized     []byte                                                        `json:"-"`
}

func (m *CommandSelectionBehaviorArchive) Reset()         { *m = CommandSelectionBehaviorArchive{} }
func (m *CommandSelectionBehaviorArchive) String() string { return proto.CompactTextString(m) }
func (*CommandSelectionBehaviorArchive) ProtoMessage()    {}

func (m *CommandSelectionBehaviorArchive) GetModelForSelection() *TSP.Reference {
	if m != nil {
		return m.ModelForSelection
	}
	return nil
}

func (m *CommandSelectionBehaviorArchive) GetType() CommandSelectionBehaviorArchive_CommandSelectionBehaviorType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return CommandSelectionBehaviorArchive_Constructive
}

func (m *CommandSelectionBehaviorArchive) GetArchivedSelection() *TSP.Reference {
	if m != nil {
		return m.ArchivedSelection
	}
	return nil
}

func (m *CommandSelectionBehaviorArchive) GetArchivedNewSelection() *TSP.Reference {
	if m != nil {
		return m.ArchivedNewSelection
	}
	return nil
}

type ImageReplaceCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ImageReplaceCommandArchive) Reset()         { *m = ImageReplaceCommandArchive{} }
func (m *ImageReplaceCommandArchive) String() string { return proto.CompactTextString(m) }
func (*ImageReplaceCommandArchive) ProtoMessage()    {}

func (m *ImageReplaceCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

type DrawableLockCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	Lock             *bool               `protobuf:"varint,3,opt,name=lock" json:"lock,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *DrawableLockCommandArchive) Reset()         { *m = DrawableLockCommandArchive{} }
func (m *DrawableLockCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawableLockCommandArchive) ProtoMessage()    {}

func (m *DrawableLockCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableLockCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableLockCommandArchive) GetLock() bool {
	if m != nil && m.Lock != nil {
		return *m.Lock
	}
	return false
}

type DrawableInfoCommentCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info             *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	OldComment       *TSP.Reference      `protobuf:"bytes,3,opt,name=old_comment" json:"old_comment,omitempty"`
	NewComment       *TSP.Reference      `protobuf:"bytes,4,opt,name=new_comment" json:"new_comment,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *DrawableInfoCommentCommandArchive) Reset()         { *m = DrawableInfoCommentCommandArchive{} }
func (m *DrawableInfoCommentCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawableInfoCommentCommandArchive) ProtoMessage()    {}

func (m *DrawableInfoCommentCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableInfoCommentCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableInfoCommentCommandArchive) GetOldComment() *TSP.Reference {
	if m != nil {
		return m.OldComment
	}
	return nil
}

func (m *DrawableInfoCommentCommandArchive) GetNewComment() *TSP.Reference {
	if m != nil {
		return m.NewComment
	}
	return nil
}

type CommentStorageApplyCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	CommentStorage   *TSP.Reference      `protobuf:"bytes,2,req,name=comment_storage" json:"comment_storage,omitempty"`
	CommentString    *string             `protobuf:"bytes,3,req,name=comment_string" json:"comment_string,omitempty"`
	OldCommentString *string             `protobuf:"bytes,4,req,name=old_comment_string" json:"old_comment_string,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *CommentStorageApplyCommandArchive) Reset()         { *m = CommentStorageApplyCommandArchive{} }
func (m *CommentStorageApplyCommandArchive) String() string { return proto.CompactTextString(m) }
func (*CommentStorageApplyCommandArchive) ProtoMessage()    {}

func (m *CommentStorageApplyCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *CommentStorageApplyCommandArchive) GetCommentStorage() *TSP.Reference {
	if m != nil {
		return m.CommentStorage
	}
	return nil
}

func (m *CommentStorageApplyCommandArchive) GetCommentString() string {
	if m != nil && m.CommentString != nil {
		return *m.CommentString
	}
	return ""
}

func (m *CommentStorageApplyCommandArchive) GetOldCommentString() string {
	if m != nil && m.OldCommentString != nil {
		return *m.OldCommentString
	}
	return ""
}

type GuideCommandArchive struct {
	Super            *TSK.CommandArchive                   `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Storage          *TSP.Reference                        `protobuf:"bytes,2,opt,name=storage" json:"storage,omitempty"`
	OldGuide         *UserDefinedGuideArchive              `protobuf:"bytes,3,opt,name=old_guide" json:"old_guide,omitempty"`
	NewGuide         *UserDefinedGuideArchive              `protobuf:"bytes,4,opt,name=new_guide" json:"new_guide,omitempty"`
	Mode             *GuideCommandArchive_GuideCommandMode `protobuf:"varint,5,opt,name=mode,enum=GuideCommandArchive_GuideCommandMode" json:"mode,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *GuideCommandArchive) Reset()         { *m = GuideCommandArchive{} }
func (m *GuideCommandArchive) String() string { return proto.CompactTextString(m) }
func (*GuideCommandArchive) ProtoMessage()    {}

func (m *GuideCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *GuideCommandArchive) GetStorage() *TSP.Reference {
	if m != nil {
		return m.Storage
	}
	return nil
}

func (m *GuideCommandArchive) GetOldGuide() *UserDefinedGuideArchive {
	if m != nil {
		return m.OldGuide
	}
	return nil
}

func (m *GuideCommandArchive) GetNewGuide() *UserDefinedGuideArchive {
	if m != nil {
		return m.NewGuide
	}
	return nil
}

func (m *GuideCommandArchive) GetMode() GuideCommandArchive_GuideCommandMode {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return GuideCommandArchive_Add
}

type DrawableAspectRatioLockedCommandArchive struct {
	Super             *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info              *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	AspectRatioLocked *bool               `protobuf:"varint,3,opt,name=aspect_ratio_locked" json:"aspect_ratio_locked,omitempty"`
	XXX_unrecognized  []byte              `json:"-"`
}

func (m *DrawableAspectRatioLockedCommandArchive) Reset() {
	*m = DrawableAspectRatioLockedCommandArchive{}
}
func (m *DrawableAspectRatioLockedCommandArchive) String() string { return proto.CompactTextString(m) }
func (*DrawableAspectRatioLockedCommandArchive) ProtoMessage()    {}

func (m *DrawableAspectRatioLockedCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableAspectRatioLockedCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableAspectRatioLockedCommandArchive) GetAspectRatioLocked() bool {
	if m != nil && m.AspectRatioLocked != nil {
		return *m.AspectRatioLocked
	}
	return false
}

type DrawableAccessibilityDescriptionCommandArchive struct {
	Super                    *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Info                     *TSP.Reference      `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	AccessibilityDescription *string             `protobuf:"bytes,3,opt,name=accessibility_description" json:"accessibility_description,omitempty"`
	XXX_unrecognized         []byte              `json:"-"`
}

func (m *DrawableAccessibilityDescriptionCommandArchive) Reset() {
	*m = DrawableAccessibilityDescriptionCommandArchive{}
}
func (m *DrawableAccessibilityDescriptionCommandArchive) String() string {
	return proto.CompactTextString(m)
}
func (*DrawableAccessibilityDescriptionCommandArchive) ProtoMessage() {}

func (m *DrawableAccessibilityDescriptionCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *DrawableAccessibilityDescriptionCommandArchive) GetInfo() *TSP.Reference {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *DrawableAccessibilityDescriptionCommandArchive) GetAccessibilityDescription() string {
	if m != nil && m.AccessibilityDescription != nil {
		return *m.AccessibilityDescription
	}
	return ""
}

type PasteStyleCommandArchive struct {
	Super            *TSK.CommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	DestInfo         *TSP.Reference      `protobuf:"bytes,2,req,name=dest_info" json:"dest_info,omitempty"`
	ShapeStyle       *TSP.Reference      `protobuf:"bytes,3,opt,name=shape_style" json:"shape_style,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *PasteStyleCommandArchive) Reset()         { *m = PasteStyleCommandArchive{} }
func (m *PasteStyleCommandArchive) String() string { return proto.CompactTextString(m) }
func (*PasteStyleCommandArchive) ProtoMessage()    {}

func (m *PasteStyleCommandArchive) GetSuper() *TSK.CommandArchive {
	if m != nil {
		return m.Super
	}
	return nil
}

func (m *PasteStyleCommandArchive) GetDestInfo() *TSP.Reference {
	if m != nil {
		return m.DestInfo
	}
	return nil
}

func (m *PasteStyleCommandArchive) GetShapeStyle() *TSP.Reference {
	if m != nil {
		return m.ShapeStyle
	}
	return nil
}

func init() {
	proto.RegisterEnum("MovieSetValueCommandArchive_LoopOption", MovieSetValueCommandArchive_LoopOption_name, MovieSetValueCommandArchive_LoopOption_value)
	proto.RegisterEnum("DrawablesCommandGroupArchive_DrawablesCommandGroupType", DrawablesCommandGroupArchive_DrawablesCommandGroupType_name, DrawablesCommandGroupArchive_DrawablesCommandGroupType_value)
	proto.RegisterEnum("CommandSelectionBehaviorArchive_CommandSelectionBehaviorType", CommandSelectionBehaviorArchive_CommandSelectionBehaviorType_name, CommandSelectionBehaviorArchive_CommandSelectionBehaviorType_value)
	proto.RegisterEnum("GuideCommandArchive_GuideCommandMode", GuideCommandArchive_GuideCommandMode_name, GuideCommandArchive_GuideCommandMode_value)
}
